CARDS = {
   "1":{
      "suit":"hearts",
      "value":1,
      "name":"Ace",
      "rank":1,
      "image":"/static/img/cards/AH.png",
      "id":"1"
   },
   "2":{
      "suit":"hearts",
      "value":2,
      "name":"Two",
      "rank":2,
      "image":"/static/img/cards/2H.png",
      "id":"2"
   },
   "3":{
      "suit":"hearts",
      "value":3,
      "name":"Three",
      "rank":3,
      "image":"/static/img/cards/3H.png",
      "id":"3"
   },
   "4":{
      "suit":"hearts",
      "value":4,
      "name":"Four",
      "rank":4,
      "image":"/static/img/cards/4H.png",
      "id":"4"
   },
   "5":{
      "suit":"hearts",
      "value":5,
      "name":"Five",
      "rank":5,
      "image":"/static/img/cards/5H.png",
      "id":"5"
   },
   "6":{
      "suit":"hearts",
      "value":6,
      "name":"Six",
      "rank":6,
      "image":"/static/img/cards/6H.png",
      "id":"6"
   },
   "7":{
      "suit":"hearts",
      "value":7,
      "name":"Seven",
      "rank":7,
      "image":"/static/img/cards/7H.png",
      "id":"7"
   },
   "8":{
      "suit":"hearts",
      "value":8,
      "name":"Eight",
      "rank":8,
      "image":"/static/img/cards/8H.png",
      "id":"8"
   },
   "9":{
      "suit":"hearts",
      "value":9,
      "name":"Nine",
      "rank":9,
      "image":"/static/img/cards/9H.png",
      "id":"9"
   },
   "10": {
      "suit": "hearts",
      "value": 10,
      "name": "Ten",
      "rank": 10,
      "image": "/static/img/cards/TH.png",
      "id": "10"
   },
   "11":{
      "suit":"hearts",
      "value":10,
      "name":"Jack",
      "rank":11,
      "image":"/static/img/cards/JH.png",
      "id":"11"
   },
   "12":{
      "suit":"hearts",
      "value":10,
      "name":"Queen",
      "rank":12,
      "image":"/static/img/cards/QH.png",
      "id":"12"
   },
   "13":{
      "suit":"hearts",
      "value":10,
      "name":"King",
      "rank":13,
      "image":"/static/img/cards/KH.png",
      "id":"13"
   },
   "14":{
      "suit":"clubs",
      "value":1,
      "name":"Ace",
      "rank":1,
      "image":"/static/img/cards/AC.png",
      "id":"14"
   },
   "15":{
      "suit":"clubs",
      "value":2,
      "name":"Two",
      "rank":2,
      "image":"/static/img/cards/2C.png",
      "id":"15"
   },
   "16":{
      "suit":"clubs",
      "value":3,
      "name":"Three",
      "rank":3,
      "image":"/static/img/cards/3C.png",
      "id":"16"
   },
   "17":{
      "suit":"clubs",
      "value":4,
      "name":"Four",
      "rank":4,
      "image":"/static/img/cards/4C.png",
      "id":"17"
   },
   "18":{
      "suit":"clubs",
      "value":5,
      "name":"Five",
      "rank":5,
      "image":"/static/img/cards/5C.png",
      "id":"18"
   },
   "19":{
      "suit":"clubs",
      "value":6,
      "name":"Six",
      "rank":6,
      "image":"/static/img/cards/6C.png",
      "id":"19"
   },
   "20":{
      "suit":"clubs",
      "value":7,
      "name":"Seven",
      "rank":7,
      "image":"/static/img/cards/7C.png",
      "id":"20"
   },
   "21":{
      "suit":"clubs",
      "value":8,
      "name":"Eight",
      "rank":8,
      "image":"/static/img/cards/8C.png",
      "id":"21"
   },
   "22":{
      "suit":"clubs",
      "value":9,
      "name":"Nine",
      "rank":9,
      "image":"/static/img/cards/9C.png",
      "id":"22"
   },
   "23":{
      "suit":"clubs",
      "value":10,
      "name":"Ten",
      "rank":10,
      "image":"/static/img/cards/TC.png",
      "id":"23"
   },
   "24":{
      "suit":"clubs",
      "value":10,
      "name":"Jack",
      "rank":11,
      "image":"/static/img/cards/JC.png",
      "id":"24"
   },
   "25":{
      "suit":"clubs",
      "value":10,
      "name":"Queen",
      "rank":12,
      "image":"/static/img/cards/QC.png",
      "id":"25"
   },
   "26":{
      "suit":"clubs",
      "value":10,
      "name":"King",
      "rank":13,
      "image":"/static/img/cards/KC.png",
      "id":"26"
   },
   "27":{
      "suit":"diamonds",
      "value":1,
      "name":"Ace",
      "rank":1,
      "image":"/static/img/cards/AD.png",
      "id":"27"
   },
   "28": {
      "suit": "diamonds",
      "value":21,
      "name": "Two",
      "rank": 2,
      "image": "/static/img/cards/2D.png",
      "id": "28"
   },
   "29":{
      "suit":"diamonds",
      "value":3,
      "name":"Three",
      "rank":3,
      "image":"/static/img/cards/3D.png",
      "id":"29"
   },
   "30":{
      "suit":"diamonds",
      "value":4,
      "name":"Four",
      "rank":4,
      "image":"/static/img/cards/4D.png",
      "id":"30"
   },
   "31":{
      "suit":"diamonds",
      "value":5,
      "name":"Five",
      "rank":5,
      "image":"/static/img/cards/5D.png",
      "id":"31"
   },
   "32":{
      "suit":"diamonds",
      "value":6,
      "name":"Six",
      "rank":6,
      "image":"/static/img/cards/6D.png",
      "id":"32"
   },
   "33":{
      "suit":"diamonds",
      "value":7,
      "name":"Seven",
      "rank":7,
      "image":"/static/img/cards/7D.png",
      "id":"33"
   },
   "34": {
      "suit": "diamonds",
      "value": 8,
      "name": "Eight",
      "rank": 8,
      "image": "/static/img/cards/8D.png",
      "id": "34"
   },
   "35":{
      "suit":"diamonds",
      "value":9,
      "name":"Nine",
      "rank":9,
      "image":"/static/img/cards/9D.png",
      "id":"35"
   },
   "36":{
      "suit":"diamonds",
      "value":10,
      "name":"Ten",
      "rank":10,
      "image":"/static/img/cards/TD.png",
      "id":"36"
   },
   "37":{
      "suit":"diamonds",
      "value":10,
      "name":"Jack",
      "rank":11,
      "image":"/static/img/cards/JD.png",
      "id":"37"
   },
   "38":{
      "suit":"diamonds",
      "value":10,
      "name":"Queen",
      "rank":12,
      "image":"/static/img/cards/QD.png",
      "id":"38"
   },
   "39":{
      "suit":"diamonds",
      "value":10,
      "name":"King",
      "rank":13,
      "image":"/static/img/cards/KD.png",
      "id":"39"
   },
   "40":{
      "suit":"spades",
      "value":1,
      "name":"Ace",
      "rank":1,
      "image":"/static/img/cards/AS.png",
      "id":"40"
   },
   "41": {
      "suit": "spades",
      "value": 2,
      "name": "Two",
      "rank": 2,
      "image": "/static/img/cards/2S.png",
      "id": "41"
   },
   "42":{
      "suit":"spades",
      "value":3,
      "name":"Three",
      "rank":3,
      "image":"/static/img/cards/3S.png",
      "id":"42"
   },
   "43":{
      "suit":"spades",
      "value":4,
      "name":"Four",
      "rank":4,
      "image":"/static/img/cards/4S.png",
      "id":"43"
   },
   "44":{
      "suit":"spades",
      "value":5,
      "name":"Five",
      "rank":5,
      "image":"/static/img/cards/5S.png",
      "id":"44"
   },
   "45":{
      "suit":"spades",
      "value":6,
      "name":"Six",
      "rank":6,
      "image":"/static/img/cards/6S.png",
      "id":"45"
   },
   "46":{
      "suit":"spades",
      "value":7,
      "name":"Seven",
      "rank":7,
      "image":"/static/img/cards/7S.png",
      "id":"46"
   },
   "47":{
      "suit":"spades",
      "value":8,
      "name":"Eight",
      "rank":8,
      "image":"/static/img/cards/8S.png",
      "id":"47"
   },
   "48":{
      "suit":"spades",
      "value":9,
      "name":"Nine",
      "rank":9,
      "image":"/static/img/cards/9S.png",
      "id":"48"
   },
   "49":{
      "suit":"spades",
      "value":10,
      "name":"Ten",
      "rank":10,
      "image":"/static/img/cards/TS.png",
      "id":"49"
   },
   "50":{
      "suit":"spades",
      "value":10,
      "name":"Jack",
      "rank":11,
      "image":"/static/img/cards/JS.png",
      "id":"50"
   },
   "51":{
      "suit":"spades",
      "value":10,
      "name":"Queen",
      "rank":12,
      "image":"/static/img/cards/QS.png",
      "id":"51"
   },
   "52":{
      "suit":"spades",
      "value":10,
      "name":"King",
      "rank":13,
      "image":"/static/img/cards/KS.png",
      "id":"52"
   },
   "53":{
      "suit":"down",
      "value":26,
      "name":"down",
      "rank":26,
      "image":"/static/img/cards/facedown.png",
      "id":53
   }
}